global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'storage-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['storage-service:8020']

  - job_name: 'websocket-service'
    metrics_path: /health
    static_configs:
      - targets: ['websocket-service:8030']

  - job_name: 'graph-state'
    metrics_path: /health
    static_configs:
      - targets: ['graph-state:8010']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
